modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="liminal_space"
version="1.0"
displayName="Liminal space"
displayURL="https://github.com/StreamingJess/Liminal_Spaces/tree/master"
credits="Created by Jess, Ariana, Rporotos"
authors="Jess"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.liminal_space]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
